services:
    db:
        image: postgres:16-alpine
        ports:
            - 10100:5432
        environment:
            POSTGRES_USER: soc
            POSTGRES_PASSWORD: password
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U soc"]
            interval: 2s
            timeout: 1s
            retries: 5
        volumes:
            - db-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: soc@example.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_DISABLE_POSTFIX: true
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
        volumes:
            - ./postgres/servers.json:/pgadmin4/servers.json

volumes:
    db-data:
